from osm.osm import OSM
from osm.osm_content_handler import OSMContentHandler

from osm2cityjson.osm2cityjson import OSM2CityJSON

from tests import BaseTest


class TestOSM2CityJSON(BaseTest):
    def setUp(self):
        self._make_test_dir(self.test_output_dir)
        self.input_filepath = self.fixture_dir / "sample-buildings.osm"
        self.handler = OSMContentHandler()
        self.osm = OSM(self.input_filepath, self.handler, self.logger)
        self.ways, self.nodes = self.osm.run()
        self.cityjson_path = self.test_output_dir / "sample-buildings.cityjson"

    def test_run(self):
        osm2cityjson = OSM2CityJSON(self.ways, self.nodes, self.logger,
                                    self.cityjson_path)
        osm2cityjson.run()
        ## Need more test. Currently file generated by it doens't pass
        # val2dity test. Need to figure out with cityjson folks.